[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "openjev-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
engine = { path = "../../crates/engine" }
models = { path = "../../crates/models" }
pipeline = { path = "../../crates/pipeline" }
timing = { path = "../../crates/timing" }
